import LandingPage from "./LandingPage";
import LoanCalculatorPage from "./LoanCalculatorPage";
import Faqs from "./Faqs";
import Register from "./Register";
import VerifyEmail from "./VerifyEmail";
import Login from "./Login";
import PersonalDetails from "./PersonalDetails";
import HowItWorks from "./HowItWorks";
import AboutUs from "./AboutUs";
import AddBusiness from "./add_a_business/AddBusiness";
import UploadDocs from "./add_a_business/UploadDocs";
import LoanApplication from "./LoanApplication/LoanApplication";
import BusinessDetails from "./LoanApplication/BusineesDetails";
import ReviewApplication from "./LoanApplication/ReviewApplication";
import UploadDocuments from "./LoanApplication/UploadDocuments";
import UserHome from "./UserHome";
import ProfilePage from "./ProfilePage";
import ContactPage from "./ContactPage";
import DashboardContactPage from "../context/DashboardContactPage";

export { LandingPage, LoanCalculatorPage, Faqs, Register, VerifyEmail, Login, PersonalDetails, HowItWorks, AboutUs, AddBusiness, UploadDocs, LoanApplication, BusinessDetails,ReviewApplication, UploadDocuments, UserHome, ProfilePage, ContactPage, DashboardContactPage };
