import LandingPage from "./LandingPage";
import LoanCalculatorPage from "./LoanCalculatorPage";
import Faqs from "./Faqs";
import Register from "./Register";
import VerifyEmail from "./VerifyEmail";
import Login from "./Login";
import PersonalDetails from "./PersonalDetails";
import HowItWorks from "./HowItWorks";
import AboutUs from "./AboutUs";
import AddBussiness from "./AddBussiness";
export { LandingPage, LoanCalculatorPage, Faqs, Register, VerifyEmail, Login, PersonalDetails, HowItWorks, AboutUs, AddBussiness };
